name: sceneprior
channels:
  - pytorch
  - bottler
  - iopath
  - fvcore
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.7.0
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - fsspec=2022.7.1
  - fvcore=0.1.5.post20210915
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - h5py=3.6.0
  - hdf5=1.10.6
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - intel-openmp=2021.4.0
  - iopath=0.1.9
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - nvidiacub=1.10.0
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - partd=1.2.0
  - pillow=8.4.0
  - pip=22.1.2
  - portalocker=2.3.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - readline=8.1.2
  - scikit-image=0.18.3
  - scipy=1.7.3
  - setuptools=63.4.1
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.2
  - tabulate=0.8.10
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.11.2
  - torchvision=0.13.1
  - tqdm=4.62.3
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - antlr4-python3-runtime==4.8
      - async-timeout==4.0.2
      - attrs==21.4.0
      - charset-normalizer==2.0.10
      - click==8.0.3
      - colorlog==6.6.0
      - cython==0.29.32
      - docker-pycreds==0.4.0
      - einops==0.4.1
      - fonttools==4.28.5
      - frozenlist==1.2.0
      - gitdb==4.0.9
      - gitpython==3.1.26
      - hydra-colorlog==1.1.0
      - hydra-core==1.1.1
      - hydra-submitit-launcher==1.1.6
      - importlib-resources==5.4.0
      - kiwisolver==1.3.2
      - mathutils==2.81.2
      - multidict==5.2.0
      - omegaconf==2.1.1
      - opencv-python==4.5.5.64
      - pandas==1.3.5
      - pathtools==0.1.2
      - perceiver-pytorch==0.8.3
      - plotly==5.8.0
      - plyfile==0.7.4
      - promise==2.3
      - protobuf==3.19.4
      - psutil==5.9.0
      - pyparsing==3.0.6
      - pypng==0.20220715.0
      - pytorch-fast-transformers==0.4.0
      - pytz==2021.3
      - requests==2.27.1
      - rtree==1.0.0
      - seaborn==0.11.2
      - sentry-sdk==1.5.4
      - setproctitle==1.2.2
      - shapely==1.8.1.post1
      - shortuuid==1.0.8
      - smmap==5.0.0
      - submitit==1.4.1
      - tenacity==8.0.1
      - termcolor==1.1.0
      - trimesh==3.9.42
      - urllib3==1.26.8
      - vtk==9.1.0
      - wandb==0.12.11
      - wslink==1.3.1
      - yarl==1.7.2
      - yaspin==2.1.0
      - zipp==3.7.0
